package com.troshkova.portfolioprogect.visiondetector.exception;

public enum Exception {
    EXCEPTION_NO_CAMERA,
    EXCEPTION_NO_FRONT_CAMERA,
    EXCEPTION_LIB_NOT_READY,
    EXCEPTION_NO_FILE,
    EXCEPTION_IO,
    EXCEPTION_NO_FACE,
    EXCEPTION_MANY_FACES,
    EXCEPTION_STRANGE_ORIENTATION,
    EXCEPTION_NO_EYE,
    EXCEPTION_MANY_EYES
}
